"""CLI commands for PureBoot Site Agent.

Usage:
    python -m src.agent.cli init --site-id <id> --central-url <url> --token <token>
    python -m src.agent.cli start
    python -m src.agent.cli status
    python -m src.agent.cli sync

Commands:
    init    Initialize agent configuration
    start   Start the site agent
    status  Check agent and central connectivity status
    sync    Trigger manual sync with central controller
"""
import argparse
import asyncio
import json
import sys
from pathlib import Path

import aiohttp

from src.config import settings


def create_parser() -> argparse.ArgumentParser:
    """Create argument parser for CLI."""
    parser = argparse.ArgumentParser(
        prog="pureboot-agent",
        description="PureBoot Site Agent CLI",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init command
    init_parser = subparsers.add_parser(
        "init",
        help="Initialize agent configuration",
    )
    init_parser.add_argument(
        "--site-id",
        required=True,
        help="Site ID for this agent (from central controller)",
    )
    init_parser.add_argument(
        "--central-url",
        required=True,
        help="URL of central controller (e.g., http://central.example.com:8080)",
    )
    init_parser.add_argument(
        "--token",
        required=True,
        help="Registration token (from POST /api/v1/sites/{site_id}/agent-token)",
    )
    init_parser.add_argument(
        "--data-dir",
        default="/var/lib/pureboot-agent",
        help="Data directory for agent (default: /var/lib/pureboot-agent)",
    )
    init_parser.add_argument(
        "--cache-size",
        type=int,
        default=50,
        help="Cache size in GB (default: 50)",
    )

    # start command
    subparsers.add_parser(
        "start",
        help="Start the site agent",
    )

    # status command
    subparsers.add_parser(
        "status",
        help="Check agent status and connectivity",
    )

    # sync command
    subparsers.add_parser(
        "sync",
        help="Trigger manual sync with central controller",
    )

    return parser


def cmd_init(args: argparse.Namespace) -> int:
    """Initialize agent configuration."""
    print(f"Initializing PureBoot Agent for site: {args.site_id}")
    print(f"Central controller: {args.central_url}")

    # Create data directory
    data_dir = Path(args.data_dir)
    try:
        data_dir.mkdir(parents=True, exist_ok=True)
        (data_dir / "cache" / "tftp").mkdir(parents=True, exist_ok=True)
        (data_dir / "cache" / "http").mkdir(parents=True, exist_ok=True)
        print(f"Created data directory: {data_dir}")
    except PermissionError:
        print(f"ERROR: Cannot create {data_dir} - permission denied")
        print("Try running with sudo or choose a different directory")
        return 1

    # Create .env file with agent configuration
    env_file = data_dir / ".env"
    env_content = f"""# PureBoot Site Agent Configuration
# Generated by: pureboot-agent init

PUREBOOT_AGENT__MODE=agent
PUREBOOT_AGENT__SITE_ID={args.site_id}
PUREBOOT_AGENT__CENTRAL_URL={args.central_url}
PUREBOOT_AGENT__REGISTRATION_TOKEN={args.token}
PUREBOOT_AGENT__DATA_DIR={args.data_dir}
PUREBOOT_AGENT__CACHE_DIR={args.data_dir}/cache
PUREBOOT_AGENT__CACHE_MAX_SIZE_GB={args.cache_size}
PUREBOOT_TFTP__ROOT={args.data_dir}/cache/tftp
"""

    try:
        env_file.write_text(env_content)
        print(f"Created configuration file: {env_file}")
    except Exception as e:
        print(f"ERROR: Cannot write configuration: {e}")
        return 1

    print()
    print("Agent initialized successfully!")
    print()
    print("To start the agent:")
    print(f"  1. Source the environment: source {env_file}")
    print("  2. Run: python -m src.agent.cli start")
    print()
    print("Or with Docker:")
    print(f"  docker run -d \\")
    print(f"    -e PUREBOOT_AGENT__MODE=agent \\")
    print(f"    -e PUREBOOT_AGENT__SITE_ID={args.site_id} \\")
    print(f"    -e PUREBOOT_AGENT__CENTRAL_URL={args.central_url} \\")
    print(f"    -e PUREBOOT_AGENT__REGISTRATION_TOKEN={args.token} \\")
    print(f"    -p 8080:8080 -p 69:69/udp \\")
    print(f"    --cap-add NET_BIND_SERVICE \\")
    print(f"    pureboot-agent")

    return 0


def cmd_start(args: argparse.Namespace) -> int:
    """Start the site agent."""
    # Check configuration
    if not settings.is_agent_mode:
        print("ERROR: Not configured as agent")
        print("Set PUREBOOT_AGENT__MODE=agent or run 'pureboot-agent init' first")
        return 1

    if not settings.agent.site_id:
        print("ERROR: PUREBOOT_AGENT__SITE_ID not configured")
        return 1

    if not settings.agent.central_url:
        print("ERROR: PUREBOOT_AGENT__CENTRAL_URL not configured")
        return 1

    print(f"Starting PureBoot Agent for site: {settings.agent.site_id}")
    print(f"Central controller: {settings.agent.central_url}")

    # Import and run the agent
    from src.agent.main import main as agent_main

    return asyncio.run(agent_main())


async def _check_status() -> dict:
    """Check agent status and connectivity."""
    status = {
        "mode": settings.agent.mode,
        "site_id": settings.agent.site_id,
        "central_url": settings.agent.central_url,
        "registered": settings.agent.registered,
        "central_reachable": False,
        "agent_status": None,
    }

    if not settings.is_agent_mode:
        status["error"] = "Not in agent mode"
        return status

    if not settings.agent.central_url:
        status["error"] = "Central URL not configured"
        return status

    # Check central connectivity
    try:
        async with aiohttp.ClientSession() as session:
            url = f"{settings.agent.central_url}/health"
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=5)) as resp:
                if resp.status == 200:
                    status["central_reachable"] = True
                    status["central_health"] = await resp.json()
    except aiohttp.ClientError as e:
        status["central_error"] = str(e)
    except Exception as e:
        status["central_error"] = str(e)

    # Check agent status from central (if registered)
    if status["central_reachable"] and settings.agent.site_id:
        try:
            async with aiohttp.ClientSession() as session:
                url = f"{settings.agent.central_url}/api/v1/agents/{settings.agent.site_id}/status"
                async with session.get(url, timeout=aiohttp.ClientTimeout(total=5)) as resp:
                    if resp.status == 200:
                        status["agent_status"] = await resp.json()
        except Exception:
            pass

    return status


def cmd_status(args: argparse.Namespace) -> int:
    """Check agent status."""
    print("Checking PureBoot Agent status...")
    print()

    status = asyncio.run(_check_status())

    print(f"Mode:          {status['mode']}")
    print(f"Site ID:       {status.get('site_id', 'Not configured')}")
    print(f"Central URL:   {status.get('central_url', 'Not configured')}")
    print(f"Registered:    {status.get('registered', False)}")
    print()

    if status.get("error"):
        print(f"ERROR: {status['error']}")
        return 1

    if status["central_reachable"]:
        print("Central Controller: REACHABLE")
        if status.get("central_health"):
            health = status["central_health"]
            print(f"  Status: {health.get('status', 'unknown')}")
    else:
        print("Central Controller: UNREACHABLE")
        if status.get("central_error"):
            print(f"  Error: {status['central_error']}")
        return 1

    if status.get("agent_status"):
        agent = status["agent_status"]
        print()
        print(f"Agent Status from Central:")
        print(f"  Status:      {agent.get('status', 'unknown')}")
        print(f"  Last Seen:   {agent.get('last_seen_at', 'never')}")
        print(f"  Version:     {agent.get('agent_version', 'unknown')}")
        print(f"  Uptime:      {agent.get('uptime_seconds', 0)}s")

    return 0


async def _trigger_sync() -> dict:
    """Trigger manual sync with central."""
    if not settings.is_agent_mode:
        return {"error": "Not in agent mode"}

    if not settings.agent.central_url or not settings.agent.site_id:
        return {"error": "Agent not configured"}

    # For now, just send an immediate heartbeat
    # In future, this could trigger a full content sync
    from src.agent.central_client import CentralClient, AgentMetrics

    client = CentralClient(
        central_url=settings.agent.central_url,
        site_id=settings.agent.site_id,
        token=settings.agent.registration_token,
    )

    try:
        metrics = AgentMetrics(
            agent_version="cli",
            uptime_seconds=0,
            services={},
            nodes_seen_last_hour=0,
            active_boots=0,
            cache_hit_rate=0.0,
            disk_usage_percent=0.0,
            pending_sync_items=0,
            last_sync_at=None,
            conflicts_pending=0,
        )
        response = await client.heartbeat(metrics)
        return {"success": True, "commands": len(response.commands) if response.commands else 0}
    except Exception as e:
        return {"error": str(e)}
    finally:
        await client.close()


def cmd_sync(args: argparse.Namespace) -> int:
    """Trigger manual sync."""
    print("Triggering sync with central controller...")

    result = asyncio.run(_trigger_sync())

    if result.get("error"):
        print(f"ERROR: {result['error']}")
        return 1

    print("Sync completed successfully")
    if result.get("commands", 0) > 0:
        print(f"Received {result['commands']} command(s) from central")

    return 0


def main() -> int:
    """Main CLI entry point."""
    parser = create_parser()
    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    commands = {
        "init": cmd_init,
        "start": cmd_start,
        "status": cmd_status,
        "sync": cmd_sync,
    }

    cmd_func = commands.get(args.command)
    if not cmd_func:
        print(f"Unknown command: {args.command}")
        return 1

    return cmd_func(args)


if __name__ == "__main__":
    sys.exit(main())
